#define PROJECT_VERSION 3.2.1
#define PROJECT_NAME toj-core
#define PROJECT_VERSION_MAJOR 3
#define PROJECT_VERSION_MINOR 2
#define PROJECT_VERSION_PATCH 1
#define PROJECT_BUILD_TIME  2024-01-31 04:58:25
