name: web-back CI

on:
  push:
    branches:
      - web-back
  pull_request:
    branches:
      - web-back

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: 0wfXYvF8A52E~JY
          MYSQL_DATABASE: bluewhale
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: web/back/

      - name: Install Redis CLI
        run: sudo apt-get update && sudo apt-get install -y redis-tools

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h 127.0.0.1 -u root -p0wfXYvF8A52E~JY --silent; do
            echo 'Waiting for MySQL...'
            sleep 5
          done

      - name: Wait for Redis to be ready
        run: |
          until redis-cli -h localhost -p 6379 ping; do
            echo 'Waiting for Redis...'
            sleep 5
          done

      - name: Create .env.development file
        run: |
          echo DB_HOST=localhost >> web/back/.env
          echo DB_PORT=3306 >> web/back/.env
          echo DB_USERNAME=root >> web/back/.env
          echo DB_PASSWORD=0wfXYvF8A52E >> web/back/.env
          echo DB_DATABASE=bluewhale >> web/back/.env
          echo REDIS_PORT=6379 >> web/back/.env
          echo REDIS_HOST=127.0.0.1 >> web/back/.env
          echo REDIS_DB_1=1 >> web/back/.env
          echo REDIS_DB_0=0 >> web/back/.env
          echo SMTP_HOST=smtp.qq.com >> web/back/.env
          echo SMTP_PORT=465 >> web/back/.env
          echo SMTP_USER=2959346375@qq.com >> web/back/.env
          echo SMTP_PASS=wwqrkmkriolpdccc >> web/back/.env
          echo HTTP_TIMEOUT=5000 >> web/back/.env
          echo HTTP_MAX_REDIRECTS=5 >> web/back/.env
          echo JWT_SECRET=abcdef >> web/back/.env
          echo CLIENT_ORIGIN=http://localhost:3072 >> web/back/.env
          echo RECAPTCHA_SECRET=6LddetQpAAAAANsTF75DLlAN74MDtg7Ji8wuGI_q >> web/back/.env
      
      - name: Run dev
        run: npm run start:dev
        working-directory: web/back/

      - name: Build project
        run: npm run build
        working-directory: web/back/
